### ISSUE TITLE
Wiki page not convert LaTex to general text

### ISSUE THREAD

**Issue by jitendra3109** [rstats-gsoc/gsoc2017#1]
\section{Google Summer of Code}

\begin{frame}
  \frametitle{Google Summer of Code (GSOC)}
  Student gets \$5500 for writing open source code for
  3 months.
  \begin{description}
  \item[Feb] \textbf{Admins} for open source organizations e.g. R,
    Bioconductor (MUGQIC?) apply to Google.
  \item[Mar] \textbf{Mentors} suggest projects for each org.\\
    \textbf{Students} submit project proposals to Google.\\
    Google gives funding for $n$ students to an org.
  \item[April] The top $n$ students get \$500 and begin coding.
  \item[July] Midterm evaluation, pass = \$2250.
  \item[Aug] Final evaluation, pass = \$2750.
  \item[November] Orgs get \$500/student mentored.
  \end{description}

  I have participated since 2012 as an \textbf{admin} and
  \textbf{mentor} for the R project.
\end{frame}

\begin{frame}
  \frametitle{What makes a good GSOC project?}
  Coding projects should:
  \begin{itemize}
  \item Result in free/open-source software.
  \item Be 3 months of full time work for a student.
  \item Include writing documentation and tests.
  \item Not include original research.
  \end{itemize}
  Examples: 
  \begin{itemize}
  \item Mathieu/François can be \textbf{admins} for MUGQIC org.
  \item Robert/Dan can be \textbf{mentors} for a project to implement
    new features in Gemini.
  \item Any undergrad/master/PhD candidates (at McGill or not)
    can be \textbf{students}.
  \end{itemize}
  
\end{frame}

**Comment by tdhock** [comment]
this is not an issue (use LaTeX on your own computer)

**Comment by jitendra3109** [comment]
@tdhock  No no it is written on the repo.
![image](https://cloud.githubusercontent.com/assets/10773353/22741541/8e4fe5b8-ee39-11e6-9f7b-b03fac3f8ef3.png)
So need to update with markdown language or simple text
