### ISSUE TITLE
Incorrect link on GSOC page?

### ISSUE THREAD

**Issue by revodavid** [rstats-gsoc/gsoc2017#2]
The [first link](https://github.com/rstats-gsoc/gsoc2016/wiki/table-of-proposed-coding-projects) on the [GSOC page for R](https://summerofcode.withgoogle.com/organizations/4947241283354624/) shows the 2016 projects. Should that link go to the [projects list in the 2017 wiki](https://github.com/rstats-gsoc/gsoc2017/wiki/table-of-proposed-coding-projects)?

**Comment by tdhock** [comment]
thanks, it looks like this has been fixed already
